database:
  host: core_db           # TODO: change to core_db when run on docker
  port: 5432               # TODO: change to core_db when run on docker
  username: ${CORE_DB_USER}
  password: ${CORE_DB_PASS}
  database: ${CORE_DB_NAME}

mosquitto:
  host: mqtt_broker           # TODO: change to core_db when run on docker
  port: 1883
  username: ${MQTT_BROKER_USER}
  password: ${MQTT_BROKER_PASS}
  client_id: core_service
  config_topic: mcu/+/config
  firmware_topic: mcu/+/firmware
  data_topic: mcu/+/data
  control_topic: mcu/+/control
  control_response_topic: mcu/+/control/response

server:
  host: 0.0.0.0
  port: 8082
  base_path: /api/v1/core
  ws_port: ":8080"
  ws_path: "/ws"
